input:
  label: "test_data_input"
  broker:
    copies: 10
    inputs:
      - kafka_franz:
          seed_brokers:
            - "<Redpanda Kafka API URLs>"
          topics: ["<topic>"]
          consumer_group: "<consumer-group>"
          tls:
            enabled: true
          checkpoint_limit: 250000
          batching:
            count: 1000

pipeline:
  processors:
    - label: "test_data_decode"
      schema_registry_decode:
        url: "<Redpanda Schema Registry URL>"
        tls:
        avro:
          raw_unions: true
          preserve_logical_types: true
          
#Note that unlike the broker setting on the input, we have to run unique outputs due to requiring unique Snowflake channel prefixes.
output:
  label: "snowflake_table_output"
  broker:
    copies: 1
    pattern: greedy
    outputs:
    - snowflake_streaming:
        account: <Snowflake Account>
        user: <Snowflake User>
        role: <Snowflake Role>
        database: <Snowflake DB>  
        schema: <Snowflake Schema>
        table: <Snowflake table>
        private_key_file: "<Path on disk to Snowflake key>"
        private_key_pass: <passphrase>
        max_in_flight: 16 
        batching:
          count: 32000
        build_options:
          parallelism: 40
        channel_prefix: "${REDPANDA_PIPELINE_ID}-0-"
        schema_evolution:
          enabled: true
    - snowflake_streaming:
        account: <Snowflake Account>
        user: <Snowflake User>
        role: <Snowflake Role>
        database: <Snowflake DB>  
        schema: <Snowflake Schema>
        table: <Snowflake table>
        private_key_file: "<Path on disk to Snowflake key>"
        private_key_pass: <passphrase>
        max_in_flight: 16 
        batching:
          count: 32000
        build_options:
          parallelism: 40
        channel_prefix: "${REDPANDA_PIPELINE_ID}-1-"
        schema_evolution:
          enabled: true   
    - snowflake_streaming:
        account: <Snowflake Account>
        user: <Snowflake User>
        role: <Snowflake Role>
        database: <Snowflake DB>  
        schema: <Snowflake Schema>
        table: <Snowflake table>
        private_key_file: "<Path on disk to Snowflake key>"
        private_key_pass: <passphrase>
        max_in_flight: 16 
        batching:
          count: 32000
        build_options:
          parallelism: 40
        channel_prefix: "${REDPANDA_PIPELINE_ID}-2-"
        schema_evolution:
          enabled: true 
    - snowflake_streaming:
        account: <Snowflake Account>
        user: <Snowflake User>
        role: <Snowflake Role>
        database: <Snowflake DB>  
        schema: <Snowflake Schema>
        table: <Snowflake table>
        private_key_file: "<Path on disk to Snowflake key>"
        private_key_pass: <passphrase>
        max_in_flight: 16 
        batching:
          count: 32000
        build_options:
          parallelism: 40
        channel_prefix: "${REDPANDA_PIPELINE_ID}-3-"
        schema_evolution:
          enabled: true
    - snowflake_streaming:
        account: <Snowflake Account>
        user: <Snowflake User>
        role: <Snowflake Role>
        database: <Snowflake DB>  
        schema: <Snowflake Schema>
        table: <Snowflake table>
        private_key_file: "<Path on disk to Snowflake key>"
        private_key_pass: <passphrase>
        max_in_flight: 16 
        batching:
          count: 32000
        build_options:
          parallelism: 40
        channel_prefix: "${REDPANDA_PIPELINE_ID}-4-"
        schema_evolution:
          enabled: true
    - snowflake_streaming:
        account: <Snowflake Account>
        user: <Snowflake User>
        role: <Snowflake Role>
        database: <Snowflake DB>  
        schema: <Snowflake Schema>
        table: <Snowflake table>
        private_key_file: "<Path on disk to Snowflake key>"
        private_key_pass: <passphrase>
        max_in_flight: 16 
        batching:
          count: 32000
        build_options:
          parallelism: 40
        channel_prefix: "${REDPANDA_PIPELINE_ID}-5-"
        schema_evolution:
          enabled: true
    - snowflake_streaming:
        account: <Snowflake Account>
        user: <Snowflake User>
        role: <Snowflake Role>
        database: <Snowflake DB>  
        schema: <Snowflake Schema>
        table: <Snowflake table>
        private_key_file: "<Path on disk to Snowflake key>"
        private_key_pass: <passphrase>
        max_in_flight: 16 
        batching:
          count: 32000
        build_options:
          parallelism: 40
        channel_prefix: "${REDPANDA_PIPELINE_ID}-6-"
        schema_evolution:
          enabled: true
    - snowflake_streaming:
        account: <Snowflake Account>
        user: <Snowflake User>
        role: <Snowflake Role>
        database: <Snowflake DB>  
        schema: <Snowflake Schema>
        table: <Snowflake table>
        private_key_file: "<Path on disk to Snowflake key>"
        private_key_pass: <passphrase>
        max_in_flight: 16 
        batching:
          count: 32000
        build_options:
          parallelism: 40
        channel_prefix: "${REDPANDA_PIPELINE_ID}-7-"
        schema_evolution:
          enabled: true
    - snowflake_streaming:
        account: <Snowflake Account>
        user: <Snowflake User>
        role: <Snowflake Role>
        database: <Snowflake DB>  
        schema: <Snowflake Schema>
        table: <Snowflake table>
        private_key_file: "<Path on disk to Snowflake key>"
        private_key_pass: <passphrase>
        max_in_flight: 16 
        batching:
          count: 32000
        build_options:
          parallelism: 40
        channel_prefix: "${REDPANDA_PIPELINE_ID}-8-"
        schema_evolution:
          enabled: true
    - snowflake_streaming:
        account: <Snowflake Account>
        user: <Snowflake User>
        role: <Snowflake Role>
        database: <Snowflake DB>  
        schema: <Snowflake Schema>
        table: <Snowflake table>
        private_key_file: "<Path on disk to Snowflake key>"
        private_key_pass: <passphrase>
        max_in_flight: 16 
        batching:
          count: 32000
        build_options:
          parallelism: 40
        channel_prefix: "${REDPANDA_PIPELINE_ID}-9-"
        schema_evolution:
          enabled: true

metrics:
  prometheus:
    add_process_metrics: true
  mapping: ""

http:
  enabled: true
  address: 0.0.0.0:9404
  debug_endpoints: true 
